name: reappwx

on:
  workflow_dispatch:
  # schedule:
  #    - cron: '*/11 1-23 * * *'
  watch:
    types: started
  repository_dispatch:
    types: reappwx
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        QQREAD_COOKIE: ${{ secrets.QQREAD_COOKIE }}
        QQREADER_COOKIE: ${{ secrets.QQREADER_COOKIE }}
        
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/ZhiYi-N/script.git ~/script
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        if: env.QQREAD_COOKIE
        run: |
          cd ~/script
          npm install
      - name: '运行 【reappwx】'
        if: env.QQREAD_COOKIE
        run: |
          cd ~/script
          node qqreadapp.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
  dispatch:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: ' wait'
        run: |
          sleep 51m
          sleep $(($RANDOM%20))
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          event-type: reappwx
